logging:
  level:
    com.trendsellr: DEBUG
    org.springframework: ERROR
  pattern:
    console: "%d{HH:mm:ss.SSS} %highlight(%-5level) --- [%15.15t] [%C{0}] %msg%n"
spring:
  data:
    mongodb:
      host: trendsellr.ijuvafq.mongodb.net
      port: 27017
      database: trendsellr
      username: ${MONGO_USER}
      password: ${MONGO_PASSWORD}
      uri: "mongodb+srv://${MONGO_USER}:${MONGO_PASSWORD}@${spring.data.mongodb.host}/${spring.data.mongodb.database}?retryWrites=true&w=majority"