logging:
  level:
    com.trendsellr: DEBUG
    org.springframework: INFO
  pattern:
    console: "%d{HH:mm:ss.SSS} %highlight(%-5level) --- [%15.15t] [%C{0}] %msg%n"

spring:
  profiles:
    active: local

api:
  security:
    api-key: "${API_KEY:default_api_key}"
    jwt:
      secret: "${JWT_SECRET}"
      expiration-time: 86400000
    public-paths: /api/public/v1/health,/api/public/v1/auth/**