name: Release and Automatic Synchronization

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  create_release:
    if: github.event.pull_request.merged == true && startsWith(github.event.pull_request.head.ref, 'release/')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Determine and Version
        id: versioning
        run: |
          INCREMENT_TYPE="patch"
          LABELS=$(jq -r '.pull_request.labels[].name' $GITHUB_EVENT_PATH)

          if echo "$LABELS" | grep -q "release-type/major"; then
            INCREMENT_TYPE="major"
          elif echo "$LABELS" | grep -q "release-type/minor"; then
            INCREMENT_TYPE="minor"
          fi
          
          LAST_TAG=$(git describe --tags --abbrev=0 | sed 's/^v//')
          if [ -z "$LAST_TAG" ]; then
            LAST_TAG="0.0.0"
          fi
          
          echo "Latest Version: $LAST_TAG. Increment Type: $INCREMENT_TYPE"
          
          NEW_VERSION=$(echo $LAST_TAG | awk -F. -v type="$INCREMENT_TYPE" '{
              if (type == "major") { print ($1+1) ".0.0" }
              else if (type == "minor") { print $1 "." ($2+1) ".0" }
              else { print $1 "." $2 "." ($3+1) }
          }')

          echo "::set-output name=new_tag::v$NEW_VERSION"
          echo "::set-output name=increment_type::$INCREMENT_TYPE"
          
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git commit --allow-empty -m "chore(release): Publishing version $NEW_VERSION"
          git push origin main

      - name: Create Tag and Release on GitHub
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.versioning.outputs.new_tag }}
          name: Release ${{ steps.versioning.outputs.new_tag }}
          body: |
            🎉 Release generated from PR #${{ github.event.pull_request.number }}.
            Increment: ${{ steps.versioning.outputs.increment_type }}
          draft: false
          prerelease: false

  sync_develop:
    needs: create_release
    runs-on: ubuntu-latest
    steps:
      - name: Create PR for Synchronisation to Develop
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'chore: Synchronisation of main to develop post-release'
          branch: sync/main-to-develop
          base: develop
          title: 'SYNC: Synchronisation of main post-release ${{ github.sha }}'
          body: |
            This automatic PR synchronises the `main` branch (which has just received a release) with `develop`.
            
            **It should be merged as soon as possible** to prepare `develop` for the next cycle.
          labels: automated-sync